// Generated by CoffeeScript 2.0.0-beta6
void function () {
  var defaultEscodegenFormat, escodegen;
  escodegen = require('escodegen');
  defaultEscodegenFormat = {
    indent: {
      style: '  ',
      base: 0
    },
    quotes: 'auto',
    renumber: true,
    hexadecimal: true,
    parentheses: false
  };
  module.exports = function (ast, format) {
    var key, value;
    if (null == format)
      format = {};
    for (key in defaultEscodegenFormat) {
      if (!isOwn$(defaultEscodegenFormat, key))
        continue;
      value = defaultEscodegenFormat[key];
      if (null != format[key])
        format[key];
      else
        format[key] = value;
    }
    return escodegen.generate(ast, { format: format });
  };
  function isOwn$(o, p) {
    return {}.hasOwnProperty.call(o, p);
  }
}.call(this);
