// Generated by CoffeeScript 2.0.0-beta6
void function () {
  var defaultEscodegenFormat, escodegen, esmangle;
  esmangle = require('esmangle');
  escodegen = require('escodegen');
  defaultEscodegenFormat = {
    indent: {
      style: '  ',
      base: 0
    },
    quotes: 'auto',
    renumber: true,
    hexadecimal: true,
    parentheses: false
  };
  module.exports = function (ast, options) {
    var format, key, minify, value;
    if (null == options)
      options = {};
    minify = options.minify;
    delete options.minify;
    if (minify) {
      ast = esmangle.mangle(esmangle.optimize(ast), { destructive: true });
      format = escodegen.FORMAT_MINIFY;
    } else {
      format = options;
      for (key in defaultEscodegenFormat) {
        if (!isOwn$(defaultEscodegenFormat, key))
          continue;
        value = defaultEscodegenFormat[key];
        if (null != format[key])
          format[key];
        else
          format[key] = value;
      }
    }
    return escodegen.generate(ast, { format: format });
  };
  function isOwn$(o, p) {
    return {}.hasOwnProperty.call(o, p);
  }
}.call(this);
