// Generated by CoffeeScript 2.0.0-beta6
void function () {
  var buildAst, esprima, FILE_IDENTIFIER, generateFileAssignmentNode, generateFunctionBody, getLHSExportExpression, readr;
  readr = require('readr');
  esprima = require('esprima');
  FILE_IDENTIFIER = 'files';
  module.exports = function (path, options) {
    if (null == options)
      options = {};
    return buildAst(readr.sync(path, options), options);
  };
  buildAst = function (files, options) {
    var program;
    program = esprima.parse('(function(global, ' + FILE_IDENTIFIER + '){}).call(this, this, {})');
    program.body[0].expression.callee.object.body.body = generateFunctionBody(files, options);
    return program;
  };
  generateFunctionBody = function (files, options) {
    var exportExpression, fileAssignments, lhsExpression;
    fileAssignments = files.map(generateFileAssignmentNode);
    exportExpression = esprima.parse(getLHSExportExpression(options)).body[0].expression;
    lhsExpression = exportExpression.type === 'Identifier' ? {
      type: 'MemberExpression',
      computed: false,
      object: {
        type: 'Identifier',
        name: 'global'
      },
      property: {
        type: 'Identifier',
        name: exportExpression.name
      }
    } : exportExpression;
    return fileAssignments.concat({
      type: 'ExpressionStatement',
      expression: {
        type: 'AssignmentExpression',
        operator: '=',
        left: lhsExpression,
        right: {
          type: 'Identifier',
          name: FILE_IDENTIFIER
        }
      }
    });
  };
  generateFileAssignmentNode = function (file) {
    return {
      type: 'ExpressionStatement',
      expression: {
        type: 'AssignmentExpression',
        operator: '=',
        left: {
          type: 'MemberExpression',
          computed: true,
          object: {
            type: 'Identifier',
            name: FILE_IDENTIFIER
          },
          property: {
            type: 'Literal',
            value: null != file.friendlyPath ? file.friendlyPath : file.path
          }
        },
        right: {
          type: 'Literal',
          value: file.contents
        }
      }
    };
  };
  getLHSExportExpression = function (options) {
    if (options.commonjs) {
      return 'module.exports';
    } else {
      return options['export'];
    }
  };
}.call(this);
